export type DetailApplicationType = {
  financingValue: string;
  tenor: number;
  paymentMethod: string;
  loanPurposes: string;
  storages: string;
  companyName: string;
  companyNpwp: string;
  businessField: string;
  companyPhone: string;
  companyPhoneCode: string;
  companyEmail: string;
  numberOfEmployee: string;
  companyAddress: string;
  companyProvince: string;
  companyRegency: string;
  companySubdistrict: string;
  companyVillage: string;
  companyPostalCode: string;
  companyDirction: {
    fullName: string;
    email: string;
    ktpNumber: string;
    pob: string;
    dob: string;
    position: string;
    phone: string;
    phoneCode: string;
    shareholding: string;
    addressById: string;
    provinceById: string;
    regencyById: string;
    districtById: string;
    villageById: string;
    postalCodeById: string;
  }[];
};
